name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run doc
      - run: |
          git config user.email "me@bennetgallein.de"
          git config user.name "Bennet Gallein"
          git remote set-url origin https://git:${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm run prepare-release
        env:
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
